Repository assimbly/base, pull requests merged in 2023-05, with the labels that each got.

#54 Workflows
  .github/workflows/delete-packages.yml
  .github/workflows/maven-publish.yml
  .github/workflows/snapshots.yml
  bin/mac/deploy.sh
Labels: skip-release, workflows

#55 Snapshots Workflow
  .github/workflows/maven-publish.yml
  .github/workflows/snapshots.yml
  activemqBase/pom.xml
  camelBase/pom.xml
  camelComponents/pom.xml
  commonBase/pom.xml
  databaseDrivers/pom.xml
  extra/pom.xml
  pom.xml
  springBase/pom.xml
  testBase/pom.xml
  utils/pom.xml
Labels: feature

#56 Update development version action
  .github/workflows/manual-update-version.yml
Labels: feature

#51 Release 4.0.0
  .github/issue-branch.yml
  .github/workflows/manual-update-version.yml
  .github/workflows/snapshots.yml
  .github/workflows/update-version.yml
  activemqBase/pom.xml
  bin/win/checkversions.bat
  camelBase/pom.xml
  camelComponents/pom.xml
  commonBase/pom.xml
  databaseDrivers/pom.xml
  extra/pom.xml
  pom.xml
  springBase/pom.xml
  testBase/pom.xml
  utils/pom.xml
  utils/src/main/java/org/assimbly/util/DependencyUtil.java
  utils/src/main/java/org/assimbly/util/TransformUtil.java
  utils/src/main/java/org/assimbly/util/domain/AssimblyEvent.java
  utils/src/main/java/org/assimbly/util/exception/DovetailEnvironmentException.java
  utils/src/main/java/org/assimbly/util/exception/EnvironmentException.java
  utils/src/main/java/org/assimbly/util/helper/JsonHelper.java
  utils/src/main/resources/activemq.xml
  utils/src/main/resources/broker.xml
Labels: major
